### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by wutaijieing** [MatthewPierson/Ramiel#20]
2021-03-22 13:59:58.038 Ramiel[6340:37441] Waiting...
2021-03-22 14:00:00.038 Ramiel[6340:37441] Waiting...
2021-03-22 14:00:01.654 Ramiel[6340:37212] Booted device successfully!
Creating listening port 2222 for device port 44
waiting for connection
Traceback (most recent call last):
  File "/Applications/Ramiel.app/Contents/Resources/ssh/dump.py", line 3, in <module>
    import paramiko
ModuleNotFoundError: No module named 'paramiko'
Traceback (most recent call last):
  File "/Applications/Ramiel.app/Contents/Resources/ssh/dump.py", line 3, in <module>
    import paramiko
ModuleNotFoundError: No module named 'paramiko'

for Ramiel 1.0.3

 - macOS Version: [e.g. 11.2.3]
 - Machine Model: [e.g. 2020 imac]

**iOS/iPadOS Device(please complete the following information):**
 - Model: [e.g. iPhone10,3]
 - iOS Version Being Booted: [e.g. iOS 14.4]
 - Dualbooted: [e.g. Y/N]

**Comment by MatthewPierson** [comment]
Run `pip3 install --user paramiko` then try again

**Comment by greybaron** [comment]
I'm having the same issue - `No module named 'paramiko'`- despite `pip3 install --user paramiko ` reporting that paramiko is already installed

**Comment by wutaijieing** [comment]
> 運行，`pip3 install --user paramiko`然後重試

Brother, I'm sure it's installed
